### ISSUE TITLE
Duplicit warning message after adding new activity

### ISSUE THREAD

**Issue by ERRORCEK** [Matfyz-Developer-Student-Club/matfyz-activity-sport-tracker#31]
After adding new activity warning about incomplete profiles is shown twice.
Here is picture ![image](https://user-images.githubusercontent.com/19654163/99731073-a7f57900-2abd-11eb-9373-c98a66ef209f.png) If I go somewhere else e.g. dashboard, notification about added activity and one of the warnings will disappear (one still remains).
Also it would be nice to hide/remove message if user is already verified (simple **X** would be nice)

**Comment by peterkorcsok** [comment]
Thank you for reporting duplicity in warning, we will take a look and fix it as soon as possible.

As for the possibility to hide/remove the message, we planned to display this particular "system announcement" just for a few days and then turn it off - it's just to let everyone know the reason why some users might disappear from the leaders' board and why there might be a decrease in total kilometres in challenges. All other alerts should disappear automatically with a new page/reload.

**Comment by ERRORCEK** [comment]
Thanks for quick reply.

So now it is hardcoded but will be removed in a few days.
But in case there will be other announcements in future it would be nice to
have an option to hide it (but based on how long this project must be
working ostrich approach is reasonable for now :D )

št 19. 11. 2020 o 23:43 peterkorcsok <notifications@github.com> napísal(a):
